version: '3'
services:
  app:
    container_name: amacms-app
    restart: always
    build: app
    depends_on:
      - db
      - elasticsearch
    volumes: 
      - ./app:/app
    environment:
      - DB_DATABASE=amacms
      - DB_USERNAME=root
      - DB_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - ACCESS_TOKEN_SECRET
      - ELASTIC_HOST=http://elasticsearch:9200
      - ELASTIC_PASSWORD
      - PAYMENT_MERCHANT
      - PAYMENT_MOCK
  db:
    image: mysql:latest
    container_name: amacms-mysql
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=amacms
    volumes:
      - ./db-data:/var/lib/mysql
    ports: 
      - 3306:3306
    tty: true
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    container_name: amacms-elastic
    environment:
      - cluster.name=amadev_elasticsearch
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - ELASTIC_PASSWORD
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticData:/usr/share/elasticsearch/data
  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.2
    container_name: amacms-kibana
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD}
      - SERVER_BASEPATH=/kibana
  nginx:
    container_name: amacms-nginx
    image: nginx:1.19.4-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - $FULLCHAIN_PATH:/etc/ssl-files/fullchain.pem:ro
      - $PRIVKEY_PATH:/etc/ssl-files/privkey.pem:ro
    depends_on:
      - app
      - elasticsearch
      - kibana
    restart: always

volumes:
  elasticData:
    driver: local
