version: '3'
services:
  app:
    build:
      context: ./go
    volumes:
      - "./go:/go"
    container_name: amadev_app
    ports:
      - "8080:8080"
    tty: true
    depends_on:
      - db
      - elasticsearch
  db:
    image: mysql:latest
    container_name: amadev_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: amadev
    volumes:
      - ./db-data:/var/lib/mysql
    tty: true
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    container_name: amadev_elasticsearch
    environment:
      - cluster.name=amadev_elasticsearch
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticData:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.2
    container_name: amadev_kibana
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - SERVER_BASEPATH=/kibana
  nginx:
    container_name: amadev_nginx
    image: nginx:1.19.4-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - $FULLCHAIN_PATH:/etc/ssl-files/fullchain.pem:ro
      - $PRIVKEY_PATH:/etc/ssl-files/privkey.pem:ro
    depends_on:
      - app
      - elasticsearch
      - kibana
    restart: always

volumes:
  elasticData:
    driver: local
